version: '3.8'

services:
  # MongoDB service
  unikmongodb:
    image: mongo:latest
    container_name: unikmongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=logistics_db
    networks:
      - logistics-network
    restart: unless-stopped

networks:
  logistics-network:
    driver: bridge

volumes:
  mongodb_data: